name: workflow.yml
on:
  push:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate results of code analysis

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install required tools
        # Write the commands to install ReportGenerator and Stryker into your pipeline.
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          dotnet tool install -g dotnet-stryker
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run unit tests
        # Write a command to execute unit tests while collecting code coverage
        run: |
          dotnet test --collect:"XPlat Code Coverage"

      - name: Generate report
        # Use the ReportGenerator tool to generate a report from the code coverage results
        run: |
          reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coveragereport -reporttypes:Html

      - name: Run Mutation Tests
        run: |
          dotnet stryker --threshold-high 80 --threshold-low 80
      
      - name: Collect Coverage Report
        # Complete this step sp it uploads the coverage report to the artifacts - make it run always even if previous steps fail
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coveragereport

      - name: Collect Stryker Report
        # Complete this step so it uploads the Stryker report to the artifacts - make it run always even if previous steps fail
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: stryker-report
          path: "**/StrykerOutput/**"
